<?php
/**
 * This file is part of the eZSurvey extension.
 *
 * @copyright Copyright (C) eZ Systems AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 * @version //autogentag//
 */

$FunctionList = array();

$FunctionList['survey'] = array( 'name' => 'survey',
                                 'call_method' => array( 'include_file' => 'extension/ezsurvey/modules/survey/classes/ezsurvey.php',
                                                         'class' => 'eZSurvey',
                                                         'method' => 'fetchSurvey' ),
                                 'parameter_type' => 'standard',
                                 'parameters' => array ( array ( 'name' => 'id',
                                                                 'type' => 'integer',
                                                                 'required' => true ) ) );

$FunctionList['survey_result'] = array( 'name' => 'survey_result',
                                        'call_method' => array( 'include_file' => 'extension/ezsurvey/modules/survey/classes/ezsurveyresult.php',
                                                                'class' => 'eZSurveyResult',
                                                                'method' => 'fetchSurveyResult' ),
                                        'parameter_type' => 'standard',
                                        'parameters' => array ( array ( 'name' => 'result_id',
                                                                        'type' => 'integer',
                                                                        'required' => true ) ) );
$FunctionList['result_count'] = array( 'name' => 'result_count',
                                       'call_method' => array( 'include_file' => 'extension/ezsurvey/modules/survey/classes/ezsurveyresult.php',
                                                               'class' => 'eZSurveyResult',
                                                               'method' => 'fetchSurveyResultCount' ),
                                       'parameter_type' => 'standard',
                                       'parameters' => array ( array ( 'name' => 'contentobject_id',
                                                                       'type' => 'integer',
                                                                       'required' => true ),
                                                               array( 'name' => 'contentclassattribute_id',
                                                                      'type' => 'integer',
                                                                      'required' => true ),
                                                               array ( 'name' => 'language_code',
                                                                       'type' => 'integer',
                                                                       'required' => true ) ) );

$FunctionList['multiple_choice_result'] = array( 'name' => 'multiple_choice_result',
                                                 'call_method' => array( 'include_file' => 'extension/ezsurvey/modules/survey/classes/ezsurveymultiplechoice.php',
                                                                         'class' => 'eZSurveyMultipleChoice',
                                                                         'method' => 'fetchResult' ),
                                                 'parameter_type' => 'standard',
                                                 'parameters' => array( array( 'name' => 'question',
                                                                               'type' => 'object',
                                                                               'required' => true ),
                                                                        array( 'name' => 'contentobject_id',
                                                                               'type' => 'integer',
                                                                               'required' => true ),
                                                                        array( 'name' => 'contentclassattribute_id',
                                                                               'type' => 'integer',
                                                                               'required' => true ),
                                                                        array( 'name' => 'language_code',
                                                                               'type' => 'integer',
                                                                               'required' => true ),
                                                                        array( 'name' => 'metadata',
                                                                               'type' => 'array',
                                                                               'default' => false,
                                                                               'required' => false ) ) );

$FunctionList['text_entry_result'] = array( 'name' => 'text_entry_result',
                                            'call_method' => array( 'include_file' => 'extension/ezsurvey/modules/survey/classes/ezsurveyentry.php',
                                                                    'class' => 'eZSurveyEntry',
                                                                    'method' => 'fetchResult' ),
                                            'parameter_type' => 'standard',
                                            'parameters' => array( array( 'name' => 'question',
                                                                          'type' => 'object',
                                                                          'required' => true ),
                                                                   array( 'name' => 'contentobject_id',
                                                                          'type' => 'integer',
                                                                          'required' => true ),
                                                                   array( 'name' => 'contentclassattribute_id',
                                                                          'type' => 'integer',
                                                                          'required' => true ),
                                                                   array( 'name' => 'language_code',
                                                                          'type' => 'integer',
                                                                          'required' => true ),
                                                                   array( 'name' => 'metadata',
                                                                          'type' => 'array',
                                                                          'default' => false,
                                                                          'required' => false ),
                                                                   array( 'name' => 'limit',
                                                                          'type' => 'integer',
                                                                          'default' => false,
                                                                          'required' => false ),
                                                                   array( 'name' => 'sort_by',
                                                                          'type' => 'array',
                                                                          'required' => false,
                                                                          'default' => false ) ) );

$FunctionList['multiple_choice_result_item'] = array( 'name' => 'multiple_choice_result_item' ,
                                                      'call_method' => array( 'include_file' => 'extension/ezsurvey/modules/survey/classes/ezsurveymultiplechoice.php',
                                                                              'class' => 'eZSurveyMultipleChoice',
                                                                              'method' => 'fetchResultItem' ),
                                                      'parameter_type' => 'standard',
                                                      'parameters' => array( array( 'name' => 'question',
                                                                                    'type' => 'object',
                                                                                    'required' => true ),
                                                                             array( 'name' => 'result_id',
                                                                                    'type' => 'integer',
                                                                                    'required' => true ),
                                                                             array( 'name' => 'metadata',
                                                                                    'type' => 'array',
                                                                                    'default' => false,
                                                                                    'required' => false ) ) );

$FunctionList['text_entry_result_item'] = array( 'name' => 'text_entry_result_item',
                                                 'call_method' => array( 'include_file' => 'extension/ezsurvey/modules/survey/classes/ezsurveyentry.php',
                                                                         'class' => 'eZSurveyEntry',
                                                                         'method' => 'fetchResultItem' ),
                                                 'parameter_type' => 'standard',
                                                 'parameters' => array( array( 'name' => 'question',
                                                                               'type' => 'object',
                                                                               'required' => true ),
                                                                        array( 'name' => 'result_id',
                                                                               'type' => 'integer',
                                                                               'required' => true ),
                                                                        array( 'name' => 'metadata',
                                                                               'type' => 'array',
                                                                               'default' => false,
                                                                               'required' => false ) ) );

$FunctionList['already_posted'] = array( 'name' => 'already_posted',
                                         'call_method' => array( 'include_file' => 'extension/ezsurvey/modules/survey/classes/ezsurveyresult.php',
                                                                 'class' => 'eZSurveyResult',
                                                                 'method' => 'fetchAlreadyPosted' ),
                                         'parameter_type' => 'standard',
                                         'parameters' => array( array( 'name' => 'survey_id',
                                                                       'type' => 'integer',
                                                                       'required' => true ),
                                                                array( 'name' => 'user_id',
                                                                       'type' => 'integer',
                                                                       'required' => false,
                                                                       'default' => false ) ) );
?>
